/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package THAI;

import DUNG.QuanLyDonHang;
import KHOI.KhachHangJPanel;
import PHU.SanPhamJPanel;
import SOn.NhanVienJPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class TrangChu extends javax.swing.JFrame {
private QuanLyDonHang qld;
private KhachHangJPanel kh;
private SanPhamJPanel sp;
private NhanVienJPanel nv;
    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnDonHang = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tabMain = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuThoat = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniNhanVien = new javax.swing.JMenuItem();
        mniKhachHang = new javax.swing.JMenuItem();
        mniSanPham = new javax.swing.JMenuItem();
        mniDonHang = new javax.swing.JMenuItem();
        mniHoaDon = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuDoanhThu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Log out.png")); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        btnNhanVien.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\User.png")); // NOI18N
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNhanVien);

        btnKhachHang.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\User group.png")); // NOI18N
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhachHang);

        btnSanPham.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\laptop.png")); // NOI18N
        btnSanPham.setText("Sản phẩm");
        btnSanPham.setFocusable(false);
        btnSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSanPham);

        btnDonHang.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Basket.png")); // NOI18N
        btnDonHang.setText("Đơn hàng");
        btnDonHang.setFocusable(false);
        btnDonHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDonHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDonHang);

        jButton5.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Text.png")); // NOI18N
        jButton5.setText("Hóa đơn");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        mnuHeThong.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Microsoft.png")); // NOI18N
        mnuHeThong.setText("Hệ thống");

        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuDangXuat);
        mnuHeThong.add(jSeparator1);

        mnuThoat.setText("Thoát");
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuThoat);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Billboard.png")); // NOI18N
        mnuQuanLy.setText("Quản lý");

        mniNhanVien.setText("Nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNhanVien);

        mniKhachHang.setText("Khách hàng");
        mniKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhachHangActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniKhachHang);

        mniSanPham.setText("Sản phẩm");
        mniSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSanPhamActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniSanPham);

        mniDonHang.setText("Đơn hàng");
        mniDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDonHangActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniDonHang);

        mniHoaDon.setText("Hóa đơn");
        mniHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHoaDonActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniHoaDon);

        jMenuBar1.add(mnuQuanLy);

        jMenu3.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Diagram.png")); // NOI18N
        jMenu3.setText("Thống kê");

        mnuDoanhThu.setText("Doanh thu");
        jMenu3.add(mnuDoanhThu);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Info.png")); // NOI18N
        jMenu4.setText("Thông tin");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
            .addComponent(tabMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhachHangActionPerformed
        // TODO add your handling code here:
        if(kh==null){
            kh=new KhachHangJPanel();
            tabMain.addTab("Quản lý khách hàng", kh);
        }
        tabMain.setSelectedComponent(kh);
    }//GEN-LAST:event_mniKhachHangActionPerformed

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
        // TODO add your handling code here:
        new DangNhap(this, true).setVisible(true);
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
        // TODO add your handling code here:
        int chonn = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không");
        if(chonn==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mnuThoatActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        // TODO add your handling code here:
        if(nv==null){
            nv=new NhanVienJPanel();
            tabMain.addTab("Quản lý nhân viên", nv);
        }
        tabMain.setSelectedComponent(nv);
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here: 
        if(nv==null){
            nv=new NhanVienJPanel();
            tabMain.addTab("Quản lý nhân viên", nv);
        }
        tabMain.setSelectedComponent(nv);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonHangActionPerformed
        // TODO add your handling code here:
        if(qld==null){
            qld=new QuanLyDonHang();
            tabMain.addTab("Quản lý đơn hàng", qld);
        }
        tabMain.setSelectedComponent(qld);
    }//GEN-LAST:event_btnDonHangActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        if(kh==null){
            kh=new KhachHangJPanel();
            tabMain.addTab("Quản lý khách hàng", kh);
        }
        tabMain.setSelectedComponent(kh);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        // TODO add your handling code here:
        if(sp==null){
            sp=new SanPhamJPanel();
            tabMain.addTab("Quản lý sản phẩm", sp);
        }
        tabMain.setSelectedComponent(sp);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        new DangNhap(this, true).setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void mniSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSanPhamActionPerformed
        // TODO add your handling code here:
        if(sp==null){
            sp=new SanPhamJPanel();
            tabMain.addTab("Quản lý sản phẩm", sp);
        }
        tabMain.setSelectedComponent(sp);
    }//GEN-LAST:event_mniSanPhamActionPerformed

    private void mniDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDonHangActionPerformed
        // TODO add your handling code here:
        if(qld==null){
            qld=new QuanLyDonHang();
            tabMain.addTab("Quản lý đơn hàng", qld);
        }
        tabMain.setSelectedComponent(qld);
    }//GEN-LAST:event_mniDonHangActionPerformed

    private void mniHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHoaDonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mniHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDonHang;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mniDonHang;
    private javax.swing.JMenuItem mniHoaDon;
    private javax.swing.JMenuItem mniKhachHang;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniSanPham;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDoanhThu;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
