/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package THAI;

import SOn.NhanVienJFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class TrangChu extends javax.swing.JFrame {
private NewJPanel test;
private NhanVienJFrame nv;
private NewJFrame n;
    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
    }
    public void nhanvien(){
//        new NhanVienJFrame(this, true).setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tabMain = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuThoat = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuKhachHang = new javax.swing.JMenuItem();
        mnuSanPham = new javax.swing.JMenuItem();
        mnuDonHang = new javax.swing.JMenuItem();
        mnuHoaDon = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuDoanhThu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Log out.png")); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDangXuat);

        jButton1.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\User.png")); // NOI18N
        jButton1.setText("Nhân viên");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\User group.png")); // NOI18N
        jButton2.setText("Khách hàng");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\laptop.png")); // NOI18N
        jButton3.setText("Sản phẩm");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Basket.png")); // NOI18N
        jButton4.setText("Đơn hàng");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Text.png")); // NOI18N
        jButton5.setText("Hóa đơn");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        mnuHeThong.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Microsoft.png")); // NOI18N
        mnuHeThong.setText("Hệ thống");

        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuDangXuat);
        mnuHeThong.add(jSeparator1);

        mnuThoat.setText("Thoát");
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuThoat);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Billboard.png")); // NOI18N
        mnuQuanLy.setText("Quản lý");

        jMenuItem3.setText("Nhân viên");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuQuanLy.add(jMenuItem3);

        mnuKhachHang.setText("Khách hàng");
        mnuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKhachHangActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mnuKhachHang);

        mnuSanPham.setText("Sản phẩm");
        mnuQuanLy.add(mnuSanPham);

        mnuDonHang.setText("Đơn hàng");
        mnuQuanLy.add(mnuDonHang);

        mnuHoaDon.setText("Hóa đơn");
        mnuQuanLy.add(mnuHoaDon);

        jMenuBar1.add(mnuQuanLy);

        jMenu3.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Diagram.png")); // NOI18N
        jMenu3.setText("Thống kê");

        mnuDoanhThu.setText("Doanh thu");
        jMenu3.add(mnuDoanhThu);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("E:\\ChatDocUniversity\\NHOMCHATDOCMAUDACAM\\NhomChatDoc\\src\\main\\resources\\img\\Info.png")); // NOI18N
        jMenu4.setText("Thông tin");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
            .addComponent(tabMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuKhachHangActionPerformed

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
        // TODO add your handling code here:
        new DangNhap(this, true).setVisible(true);
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
        // TODO add your handling code here:
        int chonn = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không");
        if(chonn==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mnuThoatActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(n==null){
            n=new NewJFrame();
            tabMain.addTab("Thông tin test", n);
        }
        tabMain.setSelectedComponent(n);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDoanhThu;
    private javax.swing.JMenuItem mnuDonHang;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenuItem mnuHoaDon;
    private javax.swing.JMenuItem mnuKhachHang;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenuItem mnuSanPham;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
