/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SOn;

import Model.NhanVien;
import DAO.NhanVienDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author famut
 */
public class NhanVienJFrame extends javax.swing.JFrame {

    DefaultTableModel tableModel;

    /**
     * Creates new form NhanVienJFrame
     */
    public NhanVienJFrame() {
        initComponents();
        initTable();
        fillTable();
        setLocationRelativeTo(null);
    }

    public void initTable() {
        tableModel = new DefaultTableModel();
        String[] cols = new String[]{"Mã Nhân Viên", "Tên Nhân Viên", "Email", "Số Điện Thoại", "Giới Tính", "Địa Chỉ", "Ngày Sinh"};
        tableModel.setColumnIdentifiers(cols);
        tblnhanvien.setModel(tableModel);

    }

    public void fillTable() {
        tableModel.setNumRows(0);
        NhanVienDAO dao = new NhanVienDAO();
        List<NhanVien> list = dao.findAll();
        for (NhanVien nv : list) {
            tableModel.addRow(new Object[]{nv.getMaNV(), nv.getTenNV(), nv.getEmail(), nv.getSDT(), nv.getGioiTinh(), nv.getDiaChi(), nv.getNgaySinh()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdogioitinh = new javax.swing.ButtonGroup();
        txtten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnlammoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnhanvien = new javax.swing.JTable();
        btntim = new javax.swing.JButton();
        txttim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Email:");

        jLabel5.setText("Số Điện Thoại:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("NHÂN VIÊN");
        jPanel1.add(jLabel1);

        jLabel6.setText("Giới Tính:");

        rdogioitinh.add(rdonam);
        rdonam.setText("Nam");

        rdogioitinh.add(rdonu);
        rdonu.setText("Nữ");

        jLabel2.setText("Mã Nhân Viên:");

        jLabel7.setText("Địa Chỉ:");

        jLabel3.setText("Tên Nhân Viên:");

        jLabel8.setText("Ngày Sinh:");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnlammoi.setText("Làm Mới");
        btnlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlammoiActionPerformed(evt);
            }
        });

        tblnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblnhanvien);

        btntim.setText("Tìm Kiếm");
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });

        jLabel9.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttim, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(txtngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdonam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdonu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtma)
                            .addComponent(txtten)
                            .addComponent(txtemail)
                            .addComponent(txtsdt)
                            .addComponent(txtdiachi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnlammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnthem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btntim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntim)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdonam)
                                .addComponent(rdonu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnxoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnlammoi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (txtma.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã Nhân Viên Không Được Để Trống.");
            return;
        }
        NhanVienDAO nvdao = new NhanVienDAO();

        // Kiểm tra mã nhân viên có bị trùng không
        if (nvdao.checkMaNV(txtma.getText())) {
            JOptionPane.showMessageDialog(this, "Mã Nhân Viên đã tồn tại! Vui lòng nhập mã khác.");
            return;
        }
        if (txtten.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên Nhân Viên Không Được Để Trống.");
            return;
        }
        if (txtemail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email Nhân Viên Không Được Để Trống.");
            return;
        }
        if (!txtemail.getText().matches("^[A-Za-z0-9+_.-]+@gmail\\.com$")) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ. Vui lòng nhập đúng định dạng *@gmail.com*.");
            return;
        }
        if (txtsdt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số Điện thoại Nhân Viên Không Được Để Trống.");
            return;
        }
        if (!txtsdt.getText().matches("0\\d{9}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ (phải có 10 chữ số và bắt đầu bằng 0).");
            return;
        }
        if (!rdonam.isSelected() && !rdonu.isSelected()) {
            JOptionPane.showMessageDialog(this, "Giới Tính Nhân Viên Không Được Để Trống.");
            return;
        }
        if (txtdiachi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Địa Chỉ Nhân Viên Không Được Để Trống.");
            return;
        }
        if (txtngaysinh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ngày Sinh Nhân Viên Không Được Để Trống.");
            return;
        }
        try {
            NhanVien nv = new NhanVien();
            nv.setMaNV(txtma.getText());
            nv.setTenNV(txtten.getText());
            nv.setEmail(txtemail.getText());
            nv.setSDT(txtsdt.getText());
            if (rdonam.isSelected()) {
                nv.setGioiTinh("Nam");
            } else {
                nv.setGioiTinh("Nữ");
            }
            nv.setDiaChi(txtdiachi.getText());
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                sdf.setLenient(false);
                Date utilDate = sdf.parse(txtngaysinh.getText().trim());
                nv.setNgaySinh(new java.sql.Date(utilDate.getTime()));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ. Định dạng đúng: yyyy-MM-dd.");
                return;
            }

            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm Nhân Viên", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                if (nvdao.insert(nv)) {
                    JOptionPane.showMessageDialog(this, "Thêm Nhân Viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    fillTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm Nhân Viên thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (txtma.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã Nhân Viên Không Được Để Trống.");
            return;
        }
        NhanVienDAO nvdao = new NhanVienDAO();
        if (!nvdao.checkMaNV(txtma.getText())) {
            JOptionPane.showMessageDialog(this, "Mã Nhân Viên không tồn tại! Vui lòng kiểm tra lại.");
            return;
        }
        if (txtten.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên Nhân Viên Không Được Để Trống.");
            return;
        }
        if (txtemail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email Nhân Viên Không Được Để Trống.");
            return;
        }
        if (!txtemail.getText().matches("^[A-Za-z0-9+_.-]+@gmail\\.com$")) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ. Vui lòng nhập đúng định dạng *@gmail.com*.");
            return;
        }
        if (txtsdt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số Điện thoại Nhân Viên Không Được Để Trống.");
            return;
        }
        if (!txtsdt.getText().matches("0\\d{9}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ (phải có 10 chữ số và bắt đầu bằng 0).");
            return;
        }
        if (!rdonam.isSelected() && !rdonu.isSelected()) {
            JOptionPane.showMessageDialog(this, "Giới Tính Nhân Viên Không Được Để Trống.");
            return;
        }
        if (txtdiachi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Địa Chỉ Nhân Viên Không Được Để Trống.");
            return;
        }
        if (txtngaysinh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ngày Sinh Nhân Viên Không Được Để Trống.");
            return;
        }
        try {
            NhanVien nv = new NhanVien();
            nv.setMaNV(txtma.getText());
            nv.setTenNV(txtten.getText());
            nv.setEmail(txtemail.getText());
            nv.setSDT(txtsdt.getText());
            if (rdonam.isSelected()) {
                nv.setGioiTinh("Nam");
            } else {
                nv.setGioiTinh("Nữ");
            }
            nv.setDiaChi(txtdiachi.getText());
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                sdf.setLenient(false);
                Date utilDate = sdf.parse(txtngaysinh.getText().trim());
                nv.setNgaySinh(new java.sql.Date(utilDate.getTime()));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ. Định dạng đúng: yyyy-MM-dd.");
                return;
            }
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn Cập Nhập Nhân Viên", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                if (nvdao.update(nv)) {
                    JOptionPane.showMessageDialog(this, "Cập Nhập Nhân Viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    fillTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Cập Nhập Nhân Viên thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        String MaNV = txtma.getText().trim();
        if (MaNV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa nhân viên với mã: " + MaNV + "?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            NhanVien nv = new NhanVien();
            nv.setMaNV(MaNV);

            NhanVienDAO deleteNV = new NhanVienDAO();
            boolean result = deleteNV.delete(nv);

            if (result) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Mã Nhân viên không tồn tại, xóa thắt bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        fillTable();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlammoiActionPerformed
        // TODO add your handling code here:
        txttim.setText("");
        txtma.setText("");
        txtten.setText("");
        txtemail.setText("");
        txtsdt.setText("");
        rdogioitinh.clearSelection();
        txtdiachi.setText("");
        txtngaysinh.setText("");
    }//GEN-LAST:event_btnlammoiActionPerformed

    private void tblnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnhanvienMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblnhanvien.getSelectedRow();
            if (row >= 0) {
                String MaNV = (String) tblnhanvien.getValueAt(row, 0);
                NhanVienDAO nvdao = new NhanVienDAO();
                NhanVien nv = nvdao.findByID(MaNV);
                if (nv != null) {
                    txtma.setText(nv.getMaNV());
                    txtten.setText(nv.getTenNV());
                    txtemail.setText(nv.getEmail());
                    txtsdt.setText(nv.getSDT());

                    // Xử lý radio button cho giới tính
                    if ("Nam".equals(nv.getGioiTinh())) {
                        rdonam.setSelected(true);
                    } else if ("Nữ".equals(nv.getGioiTinh())) {
                        rdonu.setSelected(true);
                    }
                    txtdiachi.setText(nv.getDiaChi());
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    txtngaysinh.setText(sdf.format(nv.getNgaySinh()));

                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        fillTable();
    }//GEN-LAST:event_tblnhanvienMouseClicked

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        // TODO add your handling code here:
        String maNV = txttim.getText().trim();

        // Kiểm tra nếu mã nhân viên để trống
        if (maNV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên để tìm kiếm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            fillTable();
            return;

        }

        NhanVienDAO nvdao = new NhanVienDAO();
        NhanVien nv = nvdao.findByID(maNV);

        if (nv != null) {
            tableModel.setRowCount(0);
            tableModel.addRow(new Object[]{
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getEmail(),
                nv.getSDT(),
                nv.getGioiTinh(),
                nv.getDiaChi(),
                nv.getNgaySinh()
            });
            // Hiển thị thông tin nhân viên
            txtma.setText(nv.getMaNV());
            txtten.setText(nv.getTenNV());
            txtemail.setText(nv.getEmail());
            txtsdt.setText(nv.getSDT());

            // Xử lý radio button giới tính
            if ("Nam".equals(nv.getGioiTinh())) {
                rdonam.setSelected(true);
            } else if ("Nữ".equals(nv.getGioiTinh())) {
                rdonu.setSelected(true);
            } else {
                rdonam.setSelected(false);
                rdonu.setSelected(false);
            }

            txtdiachi.setText(nv.getDiaChi());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            txtngaysinh.setText(sdf.format(nv.getNgaySinh()));
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên theo mã");
            return;
        }
        // Thông báo tìm kiếm thành công
        JOptionPane.showMessageDialog(this, "Tìm kiếm thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btntimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlammoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntim;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup rdogioitinh;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTable tblnhanvien;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtten;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
