/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DUNG;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DonHangJFrame extends javax.swing.JFrame {

    DefaultTableModel tableModel;

    /**
     * Creates new form DonHangJFrame
     */
    public DonHangJFrame() {
        initComponents();
        init();
        loadData();
        loadMaNV();
        loadMaKH();
    }

    public void init() {
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new String[]{"Mã DH", "Mã NV", "Mã KH", "Ngày tạo", "Phương thức TT", "Tổng số lượng", "Tổng tiền"});
        tblDonHang.setModel(tableModel);
    }

    public void loadData() {
        tableModel.setRowCount(0);
        DonHangDAO dao = new DonHangDAO();
        List<DonHang> list = dao.findAll();
        for (DonHang donHang : list) {
            tableModel.addRow(new Object[]{donHang.getMaDH(),
                donHang.getMaNV(),
                donHang.getMaKH(),
                donHang.getNgayTao(),
                donHang.getPhuongThucThanhToan(),
                donHang.getTongSoLuong(),
                donHang.getTongTien()});
        }
    }

    public void loadMaNV() {
        DonHangDAO dao = new DonHangDAO();
        List<String> listMaNV = dao.getMaNV();
        cboMaNV.removeAllItems();
        for (String maNV : listMaNV) {
            cboMaNV.addItem(maNV);
        }
    }

    public void loadMaKH() {
        DonHangDAO dao = new DonHangDAO();
        List<String> listMaKH = dao.getMaKH();
        cboMaKH.removeAllItems();
        for (String maKH : listMaKH) {
            cboMaKH.addItem(maKH);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaDH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboMaNV = new javax.swing.JComboBox<>();
        cboMaKH = new javax.swing.JComboBox<>();
        txtNgayTao = new javax.swing.JTextField();
        rdoTienMat = new javax.swing.JRadioButton();
        rdoQR = new javax.swing.JRadioButton();
        txtSoLuong = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã đơn hàng");

        jLabel2.setText("Mã nhân viên");

        jLabel3.setText("Mã khách hàng");

        jLabel4.setText("Ngày tạo");

        jLabel5.setText("Phương thức thanh toán");

        jLabel6.setText("Số lượng sản phẩm mua");

        jLabel7.setText("Tổng tiền");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 255));
        jLabel8.setText("QUẢN LÝ ĐƠN HÀNG");

        cboMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaNVActionPerformed(evt);
            }
        });

        cboMaKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(rdoTienMat);
        rdoTienMat.setText("Tiền mặt");

        buttonGroup1.add(rdoQR);
        rdoQR.setText("QR code");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("Tìm kiếm");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTimKiem)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addContainerGap())
        );

        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDonHang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(60, 60, 60)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMaDH)
                                        .addComponent(cboMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboMaKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNgayTao)))
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoTienMat)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoQR)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rdoTienMat)
                            .addComponent(rdoQR))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtMaDH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã đơn hàng");
            return;
        }

        //Kiểm tra trùng mã đơn hàng
        DonHangDAO dao = new DonHangDAO();
        if (dao.checkMaDH(txtMaDH.getText())) {
            JOptionPane.showMessageDialog(this, "Mã đơn hàng đã tồn tại!");
            return;

        }
        if (txtNgayTao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày tạo đơn hàng");
            return;
        }
        if (!rdoTienMat.isSelected() && !rdoQR.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phương thức thanh toán");
            return;
        }

        try {
            DonHang dh = new DonHang();
            dh.setMaDH(txtMaDH.getText());
            dh.setMaNV((String) cboMaNV.getSelectedItem());
            dh.setMaKH((String) cboMaKH.getSelectedItem());

            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                sdf.setLenient(false);
                Date utilDate = sdf.parse(txtNgayTao.getText().trim());
                dh.setNgayTao(new java.sql.Date(utilDate.getTime()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ngày tạo không hợp lệ. Định dạng đúng: yyyy-MM-dd.");
                return;
            }
            if (rdoTienMat.isSelected()) {
                dh.setPhuongThucThanhToan("Tiền mặt");
            } else {
                dh.setPhuongThucThanhToan("QR code");
            }
            dh.setTongSoLuong(Integer.parseInt(txtSoLuong.getText()));
            dh.setTongTien(new BigDecimal(txtTongTien.getText()));

            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm đơn hàng không?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                if (dao.insert(dh)) {
                    JOptionPane.showMessageDialog(this, "Thêm đơn hàng thành công");
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm đơn hàng thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void cboMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaNVActionPerformed
        // TODO add your handling code here:
        String maNV = (String) cboMaNV.getSelectedItem();
        if (maNV != null && !maNV.isEmpty()) {
            DonHangDAO dao = new DonHangDAO();

        }
    }//GEN-LAST:event_cboMaNVActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maDH = txtMaDH.getText().trim();
        if (maDH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã đơn hàng");
            return;
        }
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá " + maDH + " ? ", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            DonHang dh = new DonHang();
            dh.setMaDH(maDH);

            DonHangDAO dao = new DonHangDAO();

            if (dao.delete(dh)) {
                JOptionPane.showMessageDialog(this, "Xoá đơn hàng thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Mã đơn hàng không tồn tại, xoá thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (txtMaDH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã đơn hàng");
            return;
        }
        DonHangDAO dao = new DonHangDAO();
        //check sự mã đơn hàng tồn tại
        if (!dao.checkMaDH(txtMaDH.getText())) {
            JOptionPane.showMessageDialog(this, "Mã đơn hàng không tồn tại!");
            return;
        }
        if (txtNgayTao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày tạo đơn hàng");
            return;
        }
        if (!rdoTienMat.isSelected() && !rdoQR.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phương thức thanh toán");
            return;
        }

        try {
            DonHang dh = new DonHang();
            dh.setMaDH(txtMaDH.getText());
            dh.setMaNV((String) cboMaNV.getSelectedItem());
            dh.setMaKH((String) cboMaKH.getSelectedItem());

            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                sdf.setLenient(false);
                Date utilDate = sdf.parse(txtNgayTao.getText().trim());
                dh.setNgayTao(new java.sql.Date(utilDate.getTime()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ngày tạo không hợp lệ. Định dạng đúng: yyyy-MM-dd.");
                return;
            }
            if (rdoTienMat.isSelected()) {
                dh.setPhuongThucThanhToan("Tiền mặt");
            } else {
                dh.setPhuongThucThanhToan("QR code");
            }
            dh.setTongSoLuong(Integer.parseInt(txtSoLuong.getText()));
            dh.setTongTien(new BigDecimal(txtTongTien.getText()));
            int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn cập nhật thông tin đơn hàng không ?", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            if (chon == JOptionPane.YES_OPTION) {
                if (dao.update(dh)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin đơn hàng thành công");
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin đơn hàng thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaDH.setText("");
        txtNgayTao.setText("");
        txtSoLuong.setText("");
        txtTongTien.setText("");
        txtTimKiem.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonHangMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblDonHang.getSelectedRow();
            if (row >= 0) {
                String maDH = (String) tblDonHang.getValueAt(row, 0);
                DonHangDAO dao = new DonHangDAO();
                DonHang dh = dao.findId(maDH);
                if (dh != null) {
                    txtMaDH.setText(dh.getMaDH());
                    cboMaNV.setSelectedItem(dh.getMaNV());
                    cboMaKH.setSelectedItem(dh.getMaKH());
                    txtNgayTao.setText(String.valueOf(dh.getNgayTao()));
                    if (dh.getPhuongThucThanhToan().equals("Tiền mặt")) {
                        rdoTienMat.setSelected(true);
                    } else {
                        rdoQR.setSelected(true);
                    }
                    txtSoLuong.setText(String.valueOf(dh.getTongSoLuong()));
                    txtTongTien.setText(String.valueOf(dh.getTongTien()));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblDonHangMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maDH = txtMaDH.getText().trim();

        if (maDH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã đơn hàng cần tìm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            loadData();
            return;
        }

        DonHangDAO dao = new DonHangDAO();
        DonHang dh = dao.findId(maDH);

        //Hiển thị lên bảng
        if (dh != null) {
            tableModel.setRowCount(0);
            tableModel.addRow(new Object[]{dh.getMaDH(),
                dh.getMaNV(),
                dh.getMaKH(),
                dh.getNgayTao(),
                dh.getPhuongThucThanhToan(),
                dh.getTongSoLuong(),
                dh.getTongTien()});
        

        //Hiển thị thông tin lên textField
        txtMaDH.setText(dh.getMaDH());
        cboMaNV.setSelectedItem(dh.getMaNV());
        cboMaKH.setSelectedItem(dh.getMaKH());
        txtNgayTao.setText(String.valueOf(dh.getNgayTao()));
        if (dh.getPhuongThucThanhToan().equals("Tiền mặt")) {
            rdoTienMat.setSelected(true);
        } else {
            rdoQR.setSelected(true);
        }
        txtSoLuong.setText(String.valueOf(dh.getTongSoLuong()));
        txtTongTien.setText(String.valueOf(dh.getTongTien()));
        }else{
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã đơn hàng");
            return;
        }
        JOptionPane.showMessageDialog(this, "Tìm kiếm thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonHangJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboMaKH;
    private javax.swing.JComboBox<String> cboMaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoQR;
    private javax.swing.JRadioButton rdoTienMat;
    private javax.swing.JTable tblDonHang;
    private javax.swing.JTextField txtMaDH;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
