/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.SanPham;
import DAO.SanPhamDAO;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class SanPhamJPanel extends javax.swing.JPanel {

    DefaultTableModel tbModel;

    /**
     * Creates new form SanPhamJPanel
     */
    public SanPhamJPanel() {
        initComponents();
        init();
        fill();
        addDocumentListeners();
    }

    public void init() {
        tbModel = new DefaultTableModel();
        tbModel.setColumnIdentifiers(new String[]{"MaSP", "TenSP", "Hang", "GiaNhap", "GiaBan", "SoLuongNhap", "ThoiGianNhapHang", "TongChiPhi", "MoTa"});
        tblbang.setModel(tbModel);
    }

    public void fill() {
        tbModel.setNumRows(0);
        SanPhamDAO spdao = new SanPhamDAO();
        List<SanPham> splist = spdao.FindAll();
        for (SanPham sp : splist) {
            tbModel.addRow(new Object[]{sp.getMasp(), sp.getTensp(), sp.getHang(), sp.getGianhap(), sp.getGiaban(), sp.getSoluongnhap(), sp.getThoigiannhaphang(), sp.getTongchiphi(), sp.getMota()});
        }
    }

    public void TinhTongChiPhiNhapHang() {
        SanPhamDAO spdao = new SanPhamDAO();
        SanPham sp = new SanPham();
        BigDecimal tongChiPhi = spdao.TongChiPhiNhapHang(sp);
        txttong.setText(tongChiPhi.toString());
    }

    //DocumentListener: Lắng nghe mọi thay đổi trong txtgianhap và txtsoluong (thêm ký tự, xóa ký tự, hoặc thay đổi nội dung).
    private void addDocumentListeners() {
        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTongChiPhi();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTongChiPhi();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTongChiPhi();
            }
        };

        txtgianhap.getDocument().addDocumentListener(documentListener);
        txtsoluong.getDocument().addDocumentListener(documentListener);
    }

    // Phương thức tính và cập nhật tổng chi phí
    private void updateTongChiPhi() {
        try {
            String giaNhapStr = txtgianhap.getText().trim();
            String soLuongStr = txtsoluong.getText().trim();
            // Kiểm tra nếu cả hai trường đều không rỗng
            if (!giaNhapStr.isEmpty() && !soLuongStr.isEmpty()) {
                BigDecimal giaNhap = new BigDecimal(giaNhapStr);
                int soLuong = Integer.parseInt(soLuongStr);
                BigDecimal tongChiPhi = giaNhap.multiply(new BigDecimal(soLuong));
                DecimalFormat df = new DecimalFormat("#,###.##");
                txttong.setText(df.format(tongChiPhi));
            } else {
                txttong.setText("");// Xóa tổng nếu một trong hai trường trống
            }
        } catch (NumberFormatException e) {
            txttong.setText("");// Xóa tổng nếu dữ liệu không hợp lệ
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbohang = new javax.swing.JComboBox<>();
        txtten = new javax.swing.JTextField();
        txtgianhap = new javax.swing.JTextField();
        txtgiaban = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtthoigian = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtmota = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbang = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ SẢN PHẨM");
        jPanel1.add(jLabel1);

        jLabel2.setText("Tìm kiếm");

        jLabel3.setText("Mã sản phẩm");

        jLabel4.setText("Tên sản phẩm");

        jLabel5.setText("Giá nhập");

        jLabel6.setText("Giá bán");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel7.setText("Hãng");

        cbohang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASUS", "DELL", "APPLE", "LENOVO" }));

        jLabel8.setText("Số lượng nhập");

        jLabel9.setText("Thời gian nhập hàng");

        jLabel10.setText("Mô tả");

        jLabel11.setText("Tổng chi phí");

        tblbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbang);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnmoi.setText("Làm mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtten)
                                    .addComponent(txtgianhap)
                                    .addComponent(txtgiaban, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txttong)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtthoigian))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(67, 67, 67)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbohang, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtmota)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbohang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtthoigian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txttong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtmota))
                    .addComponent(btnmoi))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1489, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtma.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã");
            return;
        }
        SanPhamDAO spdao = new SanPhamDAO();
        // Kiểm tra mã nhân viên có bị trùng không
        if (spdao.checkMaSP(txtma.getText())) {
            JOptionPane.showMessageDialog(this, "Mã Sản Phẩm đã tồn tại! Vui lòng nhập mã khác.");
            return;
        }
        if (txtten.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên");
            return;
        }
        if (txtgianhap.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá nhập");
            return;
        }
        if (txtgiaban.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá bán");
            return;
        }
        if (txtsoluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng");
            return;
        }
        if (txtthoigian.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thời gian");
            return;
        }
        if (txtmota.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mô tả");
            return;
        }

        try {
            SanPhamDAO dao = new SanPhamDAO();
            SanPham sp = new SanPham();
            sp.setMasp(txtma.getText());
            sp.setTensp(txtten.getText());
            sp.setHang((String) cbohang.getSelectedItem());
            sp.setGianhap(new BigDecimal(txtgianhap.getText()));
            sp.setGiaban(new BigDecimal(txtgiaban.getText()));
            sp.setSoluongnhap(Integer.parseInt(txtsoluong.getText()));
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false);
            Date utilDate = sdf.parse(txtthoigian.getText().trim());
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            sp.setThoigiannhaphang(sqlDate);
            // Lấy tổng chi phí từ txttong (đã được tính tự động)
            String TongChiPhiNhap = txttong.getText().replace(",", ""); // Loại bỏ dấu phẩy nếu có
            sp.setTongchiphi(new BigDecimal(TongChiPhiNhap));
            sp.setMota(txtmota.getText());
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm sản phẩm?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                if (dao.insert(sp)) {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    TinhTongChiPhiNhapHang();
                    fill();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (txtma.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã");
            return;
        }
        if (txtten.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên");
            return;
        }
        if (txtgianhap.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá nhập");
            return;
        }
        if (txtgiaban.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá bán");
            return;
        }
        if (txtsoluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng");
            return;
        }
        if (txtthoigian.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thời gian");
            return;
        }
        if (txttong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tổng");
            return;
        }
        if (txtmota.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mô tả");
            return;
        }

        try {
            SanPhamDAO dao = new SanPhamDAO();
            SanPham sp = new SanPham();
            sp.setMasp(txtma.getText());
            sp.setTensp(txtten.getText());
            sp.setHang((String) cbohang.getSelectedItem());
            sp.setGianhap(new BigDecimal(txtgianhap.getText()));
            sp.setGiaban(new BigDecimal(txtgiaban.getText()));
            sp.setSoluongnhap(Integer.parseInt(txtsoluong.getText()));
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false);
            Date utilDate = sdf.parse(txtthoigian.getText().trim());
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            sp.setThoigiannhaphang(sqlDate);
            // Lấy tổng chi phí từ txttong (đã được tính tự động)
            String TongChiPhiNhap = txttong.getText().replace(",", ""); // Loại bỏ dấu phẩy nếu có
            sp.setTongchiphi(new BigDecimal(TongChiPhiNhap));
            sp.setMota(txtmota.getText());

            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa sản phẩm?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                if (dao.update(sp)) {
                    JOptionPane.showMessageDialog(this, "Sửa sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    TinhTongChiPhiNhapHang();
                    fill();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa sản phẩm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (txtma.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mời nhập mã sản phẩm");
            return;
        }
        try {
            SanPhamDAO dao = new SanPhamDAO();
            SanPham sp = new SanPham();
            sp.setMasp(txtma.getText());
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa sản phẩm?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                if (dao.delete(sp)) {
                    JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    TinhTongChiPhiNhapHang();
                    fill();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa sản phẩm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        if (txttimkiem.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Điền mã sản phẩm cần tìm kiếm!");
            fill();
            return;
        }
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn tìm sản phẩm?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            try {
                List<SanPham> list = SanPhamDAO.SearchSanPham(txttimkiem.getText());
                if (list != null) {
                    tbModel.setNumRows(0);
                    for (SanPham sp : list) {
                        tbModel.addRow(new Object[]{sp.getMasp(), sp.getTensp(), sp.getHang(), sp.getGianhap(), sp.getGiaban(), sp.getSoluongnhap(), sp.getThoigiannhaphang(), sp.getTongchiphi(), sp.getMota()});
                    }
                    JOptionPane.showMessageDialog(this, "Tìm kiếm thành công");
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "Tìm kiếm thất bại");
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        txtma.setText("");
        txtten.setText("");
        txtgianhap.setText("");
        txtgiaban.setText("");
        cbohang.setSelectedItem("");
        txtsoluong.setText("");
        txtthoigian.setText("");
        txtmota.setText("");
        txttong.setText("");
        txttimkiem.setText("");
    }//GEN-LAST:event_btnmoiActionPerformed

    private void tblbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbangMouseClicked
        // TODO add your handling code here:
        int row = tblbang.getSelectedRow();
        if (row >= 0) {
            String ma = (String) tblbang.getValueAt(row, 0);
            SanPhamDAO dao = new SanPhamDAO();
            SanPham sp = dao.FindId(ma);
            txtma.setText(sp.getMasp());
            txtten.setText(sp.getTensp());
            cbohang.setSelectedItem(String.valueOf(sp.getHang()));
            txtgianhap.setText(String.valueOf(sp.getGianhap()));
            txtgiaban.setText(String.valueOf(sp.getGiaban()));
            txtsoluong.setText(String.valueOf(sp.getSoluongnhap()));
            txtthoigian.setText(String.valueOf(sp.getThoigiannhaphang()));
            txttong.setText(String.valueOf(sp.getTongchiphi()));
            txtmota.setText(sp.getMota());
        }
    }//GEN-LAST:event_tblbangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnmoi;
    private javax.swing.JComboBox<String> cbohang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbang;
    private javax.swing.JTextField txtgiaban;
    private javax.swing.JTextField txtgianhap;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtmota;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txtten;
    private javax.swing.JTextField txtthoigian;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txttong;
    // End of variables declaration//GEN-END:variables
}
