/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAO.DAOTK;
import java.awt.*;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author admin
 */
public class ThongKe extends javax.swing.JPanel {
private DefaultTableModel tbModel;
    private DAOTK dao = new DAOTK();


    public ThongKe() {
        initComponents();
        initTable();
        loadComboBoxNam();
    }
    
    private void initTable(){
        tbModel = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Sản phẩm", "Hãng", "Số lượng", "Doanh thu", "Chi phí nhập hàng", "Lợi nhuận"}
                
        );
        tblThongKe.setModel(tbModel);
    }

    private void loadComboBoxNam() {
        // Vô hiệu hóa ActionListener tạm thời để tránh gọi loadThongKeTheoNam() khi thêm item
        ActionListener[] listeners = cboNam.getActionListeners();
        for (ActionListener listener : listeners) {
            cboNam.removeActionListener(listener);
        }

        // Thêm các năm vào JComboBox
        cboNam.removeAllItems();
        for (int nam = 2022; nam <= 2025; nam++) {
            cboNam.addItem(String.valueOf(nam));
        }

        // Kích hoạt lại ActionListener
        for (ActionListener listener : listeners) {
            cboNam.addActionListener(listener);
        }
    }

    private void loadThongKeTheoNam() {
        if (cboNam.getSelectedItem() == null) {
            return; // Tránh lỗi nếu chưa có năm nào được chọn
        }

        int nam = Integer.parseInt(cboNam.getSelectedItem().toString());
        List<Object[]> danhSach = dao.thongKeTheoNam(nam);

        tbModel.setRowCount(0); // Xóa dữ liệu cũ
        DecimalFormat df = new DecimalFormat("#,###");
        double tongDoanhThu = 0.0;
        double tongSoLuong = 0.0;
        double tongChiPhiNhapHang = 0.0;
        double tongLoiNhuan = 0.0;

        try {
            if (danhSach.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không có dữ liệu thống kê cho năm " + nam + "!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Hiển thị dữ liệu lên bảng
            for (Object[] row : danhSach) {
                String tenSP = (String) row[0];
                String hang = (String) row[1];
                double soLuong = (Double) row[2];
                double doanhThu = (Double) row[3];
                double chiPhiNhapHang = (Double) row[4];
                double loiNhuan = (Double) row[5];

                // Tích lũy tổng doanh thu
                tongDoanhThu += doanhThu;
                tongSoLuong += soLuong;
                tongChiPhiNhapHang += chiPhiNhapHang;
                tongLoiNhuan += loiNhuan;
                
                tbModel.addRow(new Object[]{
                    tenSP,
                    hang,
                    df.format(soLuong),
                    df.format(doanhThu),
                    df.format(chiPhiNhapHang),
                    df.format(loiNhuan)
                });
            }

            // Thêm dòng tổng doanh thu
            tbModel.addRow(new Object[]{"Tổng", "",df.format(tongSoLuong), df.format(tongDoanhThu), df.format(tongChiPhiNhapHang),df.format(tongLoiNhuan)});

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu thống kê: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("THỐNG KÊ");
        jPanel1.add(jLabel1);

        jLabel2.setText("Năm");

        cboNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamActionPerformed(evt);
            }
        });

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sản phẩm", "Hãng", "Số lượng", "Doanh thu", "Chi phí nhập hàng", "Lợi nhuận"
            }
        ));
        jScrollPane1.setViewportView(tblThongKe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 399, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamActionPerformed
        // TODO add your handling code here:
        loadThongKeTheoNam();
    }//GEN-LAST:event_cboNamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblThongKe;
    // End of variables declaration//GEN-END:variables
}
