<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>NhomChatDoc</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <exec.mainClass>com.mycompany.nhomchatdoc.NhomChatDoc</exec.mainClass>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>8.4.1.jre8 </version>
        </dependency>
    </dependencies>
<!--    double giaNhap = Double.parseDouble(txtgianhap.getText().trim()); // Lấy Giá Nhập
        int soLuong = Integer.parseInt(txtsoluong.getText().trim()); // Lấy Số Lượng Nhập

        double tongChiPhi = giaNhap * soLuong; // Tính Tổng Chi Phí
        txttong.setText(String.valueOf(tongChiPhi)); // Hiển thị lên ô Tổng Chi Phí
    } catch (NumberFormatException e) {
        txttong.setText(""); // Nếu nhập sai (VD: nhập chữ), xóa kết quả-->
</project>