/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PHU;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author famut
 */
public class SanPhamJFrame extends javax.swing.JFrame {

    DefaultTableModel tbModel;

    /**
     * Creates new form SanPhamJFrame
     */
    public SanPhamJFrame() {
        initComponents();
        init();
        fill();
        addDocumentListeners();
    }

    public void init() {
        tbModel = new DefaultTableModel();
        tbModel.setColumnIdentifiers(new String[]{"MaSP", "TenSP", "Hang", "GiaNhap", "GiaBan", "SoLuongNhap", "ThoiGianNhapHang", "TongChiPhi", "MoTa"});
        tblbang.setModel(tbModel);
    }

    public void fill() {
        tbModel.setNumRows(0);
        SanPhamDAO spdao = new SanPhamDAO();
        List<SanPham> splist = spdao.FindAll();
        for (SanPham sp : splist) {
            tbModel.addRow(new Object[]{sp.getMasp(), sp.getTensp(), sp.getHang(), sp.getGianhap(), sp.getGiaban(), sp.getSoluongnhap(), sp.getThoigiannhaphang(), sp.getTongchiphi(), sp.getMota()});
        }
    }

    public void TinhTongChiPhiNhapHang() {
        SanPhamDAO spdao = new SanPhamDAO();
        SanPham sp = new SanPham();
        BigDecimal tongChiPhi = spdao.TongChiPhiNhapHang(sp);
        txttong.setText(tongChiPhi.toString());
    }

    //DocumentListener: Lắng nghe mọi thay đổi trong txtgianhap và txtsoluong (thêm ký tự, xóa ký tự, hoặc thay đổi nội dung).
    private void addDocumentListeners() {
        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTongChiPhi();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTongChiPhi();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTongChiPhi();
            }
        };

        txtgianhap.getDocument().addDocumentListener(documentListener);
        txtsoluong.getDocument().addDocumentListener(documentListener);
    }

    // Phương thức tính và cập nhật tổng chi phí
    private void updateTongChiPhi() {
        try {
            String giaNhapStr = txtgianhap.getText().trim();
            String soLuongStr = txtsoluong.getText().trim();
                // Kiểm tra nếu cả hai trường đều không rỗng
            if (!giaNhapStr.isEmpty() && !soLuongStr.isEmpty()) {
                BigDecimal giaNhap = new BigDecimal(giaNhapStr);
                int soLuong = Integer.parseInt(soLuongStr);
                BigDecimal tongChiPhi = giaNhap.multiply(new BigDecimal(soLuong));
                DecimalFormat df = new DecimalFormat("#,###.##");
                txttong.setText(df.format(tongChiPhi));
            } else {
                txttong.setText("");// Xóa tổng nếu một trong hai trường trống
            }
        } catch (NumberFormatException e) {
            txttong.setText("");// Xóa tổng nếu dữ liệu không hợp lệ
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtmota = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txttimkiem = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txttong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbohang = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtthoigian = new javax.swing.JTextField();
        txtgianhap = new javax.swing.JTextField();
        txtgiaban = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Mô Tả");

        txtmota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmotaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ SẢN PHẨM");
        jPanel1.add(jLabel1);

        tblbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbang);

        jButton1.setText("Them");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sua");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm kiếm");

        jButton3.setText("Xoa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Tim kiem");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã Sản Phẩm");

        jLabel11.setText("Tổng chi phí");

        txttong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttongActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên Sản Phẩm");

        jButton5.setText("Lam moi");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Hãng");

        jLabel7.setText("Giá Nhập");

        jLabel8.setText("Giá Bán");

        cbohang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASUS", "LENOVO", "DELL", "APPLE", "ACER", " " }));

        jLabel9.setText("Số Lượng Nhập");

        jLabel10.setText("Thời Gian Nhập Hàng");

        txtgianhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgianhapKeyReleased(evt);
            }
        });

        txtgiaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgiabanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtten))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txttong, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbohang, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtthoigian, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtmota, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton4))
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbohang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jButton5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txttong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(txtthoigian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(txtmota, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbangMouseClicked
        // TODO add your handling code here:
        int row = tblbang.getSelectedRow();
        if (row >= 0) {
            String ma = (String) tblbang.getValueAt(row, 0);
            SanPhamDAO dao = new SanPhamDAO();
            SanPham sp = dao.FindId(ma);
            txtma.setText(sp.getMasp());
            txtten.setText(sp.getTensp());
            cbohang.setSelectedItem(String.valueOf(sp.getHang()));
            txtgianhap.setText(String.valueOf(sp.getGianhap()));
            txtgiaban.setText(String.valueOf(sp.getGiaban()));
            txtsoluong.setText(String.valueOf(sp.getSoluongnhap()));
            txtthoigian.setText(String.valueOf(sp.getThoigiannhaphang()));
            txttong.setText(String.valueOf(sp.getTongchiphi()));
            txtmota.setText(sp.getMota());
        }
    }//GEN-LAST:event_tblbangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtma.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã");
            return;
        }
        SanPhamDAO dao=new SanPhamDAO();
        if(dao.checkMaSP(txtma.getText())){
            JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại!","Thông báo",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (txtten.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên");
            return;
        }
        if (txtgianhap.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá nhập");
            return;
        }
        if (txtgiaban.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá bán");
            return;
        }
        if (txtsoluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng");
            return;
        }
        if (txtthoigian.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thời gian");
            return;
        }
        if (txtmota.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mô tả");
            return;
        }

        try {
            SanPham sp = new SanPham();
            sp.setMasp(txtma.getText());
            sp.setTensp(txtten.getText());
            sp.setHang((String) cbohang.getSelectedItem());
            sp.setGianhap(new BigDecimal(txtgianhap.getText()));
            sp.setGiaban(new BigDecimal(txtgiaban.getText()));
            sp.setSoluongnhap(Integer.parseInt(txtsoluong.getText()));
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false);
            Date utilDate = sdf.parse(txtthoigian.getText().trim());
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            sp.setThoigiannhaphang(sqlDate);
            // Lấy tổng chi phí từ txttong (đã được tính tự động)
            String TongChiPhiNhap = txttong.getText().replace(",", ""); // Loại bỏ dấu phẩy nếu có
            sp.setTongchiphi(new BigDecimal(TongChiPhiNhap));
            sp.setMota(txtmota.getText());
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm sản phẩm?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                if (dao.insert(sp)) {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    TinhTongChiPhiNhapHang();
                    fill();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtma.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã");
            return;
        }
        if (txtten.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên");
            return;
        }
        if (txtgianhap.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá nhập");
            return;
        }
        if (txtgiaban.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá bán");
            return;
        }
        if (txtsoluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng");
            return;
        }
        if (txtthoigian.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thời gian");
            return;
        }
        if (txttong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tổng");
            return;
        }
        if (txtmota.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mô tả");
            return;
        }

        try {
            SanPhamDAO dao = new SanPhamDAO();
            SanPham sp = new SanPham();
            sp.setMasp(txtma.getText());
            sp.setTensp(txtten.getText());
            sp.setHang((String) cbohang.getSelectedItem());
            sp.setGianhap(new BigDecimal(txtgianhap.getText()));
            sp.setGiaban(new BigDecimal(txtgiaban.getText()));
            sp.setSoluongnhap(Integer.parseInt(txtsoluong.getText()));
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false);
            Date utilDate = sdf.parse(txtthoigian.getText().trim());
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            sp.setThoigiannhaphang(sqlDate);
            // Lấy tổng chi phí từ txttong (đã được tính tự động)
            String TongChiPhiNhap = txttong.getText().replace(",", ""); // Loại bỏ dấu phẩy nếu có
            sp.setTongchiphi(new BigDecimal(TongChiPhiNhap));
            sp.setMota(txtmota.getText());

            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa sản phẩm?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                if (dao.update(sp)) {
                    JOptionPane.showMessageDialog(this, "Sửa sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    TinhTongChiPhiNhapHang();
                    fill();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa sản phẩm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (txtma.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Moi nhap ma san pham");
            return;
        }
        if (txtten.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên");
            return;
        }
        if (txtgianhap.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá nhập");
            return;
        }
        if (txtgiaban.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá bán");
            return;
        }
        if (txtsoluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng");
            return;
        }
        if (txtthoigian.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thời gian");
            return;
        }
        if (txtmota.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mô tả");
            return;
        }

        try {
            SanPhamDAO dao = new SanPhamDAO();
            SanPham sp = new SanPham();
            sp.setMasp(txtma.getText());
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa sản phẩm?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                if (dao.delete(sp)) {
                    JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    TinhTongChiPhiNhapHang();
                    fill();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa sản phẩm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (txttimkiem.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Điền mã sản phẩm cần tìm kiếm!");
            fill();
            return;
        }
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn tìm sản phẩm?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            try {
                List<SanPham> list = SanPhamDAO.SearchSanPham(txttimkiem.getText());
                if (list != null) {
                    tbModel.setNumRows(0);
                    for (SanPham sp : list) {
                        tbModel.addRow(new Object[]{sp.getMasp(), sp.getTensp(), sp.getHang(), sp.getGianhap(), sp.getGiaban(), sp.getSoluongnhap(), sp.getThoigiannhaphang(), sp.getTongchiphi(), sp.getMota()});
                    }
                    JOptionPane.showMessageDialog(this, "Tìm kiếm thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Tìm kiếm thất bại");
                    return;
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txttongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttongActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txttongActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        txtma.setText("");
        txtten.setText("");
        txtgianhap.setText("");
        txtgiaban.setText("");
        cbohang.setSelectedItem("");
        txtsoluong.setText("");
        txtthoigian.setText("");
        txtmota.setText("");
        txttong.setText("");
        txttimkiem.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtgiabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgiabanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgiabanActionPerformed

    private void txtmotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmotaActionPerformed

    private void txtgianhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgianhapKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgianhapKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbohang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbang;
    private javax.swing.JTextField txtgiaban;
    private javax.swing.JTextField txtgianhap;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtmota;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txtten;
    private javax.swing.JTextField txtthoigian;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txttong;
    // End of variables declaration//GEN-END:variables
}
