/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LONG;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author famut
 */
public class DonHangChiTietJFrame extends javax.swing.JFrame {

    DefaultTableModel tableModel;

    /**
     * Creates new form DonHangChiTietJFrame
     */
    public DonHangChiTietJFrame() {
        initComponents();
        init();
        fill();
        loadMaDH();
        loadMaSP();
        addDocumentListeners();
    }

    public void init() {
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new String[]{"MaDonHangChiTiet", "MaDH", "MaSP", "So luong", "Don Gia", "Thanh Tien"});
        tblbang.setModel(tableModel);
    }

    public void fill() {
        tableModel.setNumRows(0);
        DonHangChiTietDAO dhctdao = new DonHangChiTietDAO();
        List<DonHangChiTiet> dhctlist = dhctdao.FindAll();
        for (DonHangChiTiet dhct : dhctlist) {
            tableModel.addRow(new Object[]{dhct.getMaDonHangChiTiet(), dhct.getMaDH(), dhct.getMaSP(), dhct.getSoLuong(), dhct.getDonGia(), dhct.getThanhTien()});
        }
    }

    public void loadMaSP() {
        DonHangChiTietDAO dhctdao = new DonHangChiTietDAO();
        List<String> listMaSP = dhctdao.MaSP();
        cboMaSP.removeAllItems();
        for (String mansp : listMaSP) {
            cboMaSP.addItem(mansp);
        }
    }

    public void loadMaDH() {
        DonHangChiTietDAO dhctdao = new DonHangChiTietDAO();
        List<String> listMaNV = dhctdao.MaDH();
        cboMaDH.removeAllItems();
        for (String mancc : listMaNV) {
            cboMaDH.addItem(mancc);
        }
    }

    private void updateThanhTien() {
        try {
            String giaNhapStr = txtdongia.getText().trim();
            String soLuongStr = txtsoluong.getText().trim();
            // Kiểm tra nếu cả hai trường đều không rỗng
            if (!giaNhapStr.isEmpty() && !soLuongStr.isEmpty()) {
                BigDecimal giaNhap = new BigDecimal(giaNhapStr);
                int soLuong = Integer.parseInt(soLuongStr);
                BigDecimal tongChiPhi = giaNhap.multiply(new BigDecimal(soLuong));
                DecimalFormat df = new DecimalFormat("#,###.##");
                txtthanhtien.setText(df.format(tongChiPhi));
            } else {
                txtthanhtien.setText("");// Xóa tổng nếu một trong hai trường trống
            }
        } catch (NumberFormatException e) {
            txtthanhtien.setText("");// Xóa tổng nếu dữ liệu không hợp lệ
        }
    }

    private void addDocumentListeners() {
        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateThanhTien();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateThanhTien();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateThanhTien();
            }
        };

        txtdongia.getDocument().addDocumentListener(documentListener);
        txtsoluong.getDocument().addDocumentListener(documentListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmadhct = new javax.swing.JTextField();
        cboMaDH = new javax.swing.JComboBox<>();
        cboMaSP = new javax.swing.JComboBox<>();
        txtsoluong = new javax.swing.JTextField();
        txtdongia = new javax.swing.JTextField();
        txtthanhtien = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btntimkiem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("ĐƠN HÀNG CHI TIẾT");

        jLabel2.setText("MaDHCT");

        jLabel3.setText("MaDH");

        jLabel4.setText("MaSP");

        jLabel5.setText("So Luong");

        jLabel6.setText("Don Gia");

        jLabel7.setText("Thanh Tien");

        cboMaDH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboMaSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaSPActionPerformed(evt);
            }
        });

        txtthanhtien.setEditable(false);

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btntimkiem.setText("Tìm kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        jLabel8.setText("Tim kiem");

        tblbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtmadhct, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtdongia))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtthanhtien))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboMaDH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txttimkiem)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnclear)
                    .addComponent(btntimkiem))
                .addGap(71, 71, 71))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmadhct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntimkiem)
                    .addComponent(jLabel8)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (txtmadhct.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mời nhập mã đơn hàng chi tiết");
            return;
        }
        if (txtsoluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mời nhập số lượng");
            return;
        }
        try {
            int soLuong = Integer.parseInt(txtsoluong.getText());
            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải là số lớn hơn 0");
                return;
            }
            DonHangChiTiet dhct = new DonHangChiTiet();
            dhct.setMaDonHangChiTiet(txtmadhct.getText());
            dhct.setMaDH((String) cboMaDH.getSelectedItem());
            dhct.setMaSP((String) cboMaSP.getSelectedItem());
            dhct.setSoLuong(Integer.parseInt(txtsoluong.getText()));
            dhct.setDonGia(new BigDecimal(txtdongia.getText()));
            // Lấy tổng chi phí từ txttong (đã được tính tự động)
            String TongThanhTien = txtthanhtien.getText().replace(",", ""); // Loại bỏ dấu phẩy nếu có
            dhct.setThanhTien(new BigDecimal(TongThanhTien));
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm sản phẩm không");
            if (chon == JOptionPane.YES_OPTION) {
                DonHangChiTietDAO dhctdao = new DonHangChiTietDAO();
                if (dhctdao.insert(dhct)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    fill();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void tblbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbangMouseClicked
        // TODO add your handling code here:
        int row=tblbang.getSelectedRow();
        if (row>=0) {
            String MaDHCT=(String) tblbang.getValueAt(row, 0);
            DonHangChiTietDAO dhctdao=new DonHangChiTietDAO();
            DonHangChiTiet dhct=dhctdao.FindById(MaDHCT);
            txtmadhct.setText(dhct.getMaDonHangChiTiet());
            cboMaDH.setSelectedItem(dhct.getMaDH());
            cboMaSP.setSelectedItem(dhct.getMaSP());
            txtsoluong.setText(String.valueOf(dhct.getSoLuong()));
            txtdongia.setText(String.valueOf(dhct.getDonGia()));
            txtthanhtien.setText(String.valueOf(dhct.getThanhTien()));
        }
    }//GEN-LAST:event_tblbangMouseClicked

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
         if (txtmadhct.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mời nhập mã đơn hàng chi tiết");
            return;
        }
        if (txtsoluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mời nhập số lượng");
            return;
        }
        try {
            int soLuong = Integer.parseInt(txtsoluong.getText());
            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải là số lớn hơn 0");
                return;
            }
            DonHangChiTiet dhct = new DonHangChiTiet();
            dhct.setMaDonHangChiTiet(txtmadhct.getText());
            dhct.setMaDH((String) cboMaDH.getSelectedItem());
            dhct.setMaSP((String) cboMaSP.getSelectedItem());
            dhct.setSoLuong(Integer.parseInt(txtsoluong.getText()));
            dhct.setDonGia(new BigDecimal(txtdongia.getText()));
            // Lấy tổng chi phí từ txttong (đã được tính tự động)
            String TongThanhTien = txtthanhtien.getText().replace(",", ""); // Loại bỏ dấu phẩy nếu có
            dhct.setThanhTien(new BigDecimal(TongThanhTien));
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa sản phẩm không");
            if (chon == JOptionPane.YES_OPTION) {
                DonHangChiTietDAO dhctdao = new DonHangChiTietDAO();
                if (dhctdao.update(dhct)) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    fill();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa thất bại");
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
         if (txtmadhct.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mời nhập mã đơn hàng chi tiết");
            return;
        }        
            try{
            DonHangChiTiet dhct=new DonHangChiTiet();
            dhct.setMaDonHangChiTiet(txtmadhct.getText());
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa sản phẩm không");
            if (chon == JOptionPane.YES_OPTION) {
                DonHangChiTietDAO dhctdao = new DonHangChiTietDAO();
                if (dhctdao.delete(dhct)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    fill();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
         String maDHCT = txttimkiem.getText().trim();
        if (maDHCT.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã để tìm kiếm!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            fill();
            return;
        }
        DonHangChiTietDAO dhctdao = new DonHangChiTietDAO();
        DonHangChiTiet dhct = dhctdao.FindById(maDHCT);
        if (dhct != null) {
            tableModel.setRowCount(0);
            tableModel.addRow(new Object[]{
                dhct.getMaDonHangChiTiet(),
                dhct.getMaDH(),
                dhct.getMaSP(),
                dhct.getSoLuong(),
                dhct.getDonGia(),
                dhct.getThanhTien()
            });
            txtmadhct.setText(dhct.getMaDonHangChiTiet());
            cboMaDH.setSelectedItem(dhct.getMaDH());
            cboMaSP.setSelectedItem(dhct.getMaSP());
            txtsoluong.setText(String.valueOf(dhct.getSoLuong()));
            txtdongia.setText(String.valueOf(dhct.getDonGia()));
            txtthanhtien.setText(String.valueOf(dhct.getThanhTien()));
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy đơn hàng với mã: " + maDHCT, "Thông báo", JOptionPane.ERROR_MESSAGE);
            fill();
        }
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtmadhct.setText("");
        txtsoluong.setText("");
        txtdongia.setText("");
        txtthanhtien.setText("");
        txttimkiem.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void cboMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaSPActionPerformed
        // TODO add your handling code here:
        String maSP = (String) cboMaSP.getSelectedItem();
        if (maSP != null && !maSP.isEmpty()) {
            DonHangChiTietDAO dao = new DonHangChiTietDAO();
            float GiaBan = dao.getGiaBanBySP(maSP);
            txtdongia.setText(String.valueOf(GiaBan));

        } else {
            txtdongia.setText(""); 
        }
    }//GEN-LAST:event_cboMaSPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonHangChiTietJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonHangChiTietJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonHangChiTietJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonHangChiTietJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonHangChiTietJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cboMaDH;
    private javax.swing.JComboBox<String> cboMaSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbang;
    private javax.swing.JTextField txtdongia;
    private javax.swing.JTextField txtmadhct;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txtthanhtien;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
